apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detector
spec:
  selector:
    matchLabels:
      app: obj-detector
  replicas: 1
  template:
    metadata:
      labels:
        app: obj-detector
    spec:
      containers:
      - name: objectdetector
        image: smilracr.azurecr.io/atlas/objectdetector:latest
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 5001
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
